spring.application.name=payment-intake-service
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5450/payrelay
spring.datasource.username=payrelay
spring.datasource.password=payrelay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9100